version: "3.4"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4173:4173" # NGINX default port
    networks:
      - app-network
       
   
networks:
  app-network:
    driver: bridge
